---
- name: Include OS-specific variables (Debian)
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Include OS-specific variables (RHEL)
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- name: Use systemd to set timezone
  become: true
  shell: timedatectl set-timezone "{{ systemd_timezone }}"

- name: Deploy the timesyncd template
  template:
    src: etc/systemd/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart systemd-timedated

- name: Use systemd to manage ntp
  become: true
  shell: timedatectl set-ntp "{{ systemd_ntp_enabled }}"

- name: Get timedatectl status
  shell: timedatectl status
  register: timedatectl_status

- debug:
    var: timedatectl_status
